sudo: required 
services:
 - docker 


before_install: 
 - docker build -t sabuhi1/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true sabuhi1/react-test npm test 

after_success:
 - docker build -t sabuhi1/complexapp-client ./client
 - docker build -t sabuhi1/complexapp-server ./server
 - docker build -t sabuhi1/complexapp-nginx ./nginx
 - docker build -t sabuhi1/complexapp-worker ./worker

#Log In to docker login first

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take and push to hub.docker.com 

 - docker push sabuhi1997/complexapp-client
 - docker push sabuhi1997/complexapp-server
 - docker push sabuhi1997/complexapp-nginx
 - docker push sabuhi1997/complexapp-worker

 

